[project]

# Project metadata

# -- General info
name = "WWWeather.Data-CSV"
version = "0.3.0"
description = """
WWWeather application CSV import/export adapter package:
provides WWWeather.Core weather records dumping/loading interfaces
implementations for the CSV format.
"""

# -- README file
readme = "README.md"

# -- Required Python version
requires-python = ">=3.10"

# -- Required pip packages
dependencies = [
    "WWWeather.Core==0.3.0"
]


[build-system]

# Project build backend

requires = ["setuptools >= 69.0.0"]
build-backend = "setuptools.build_meta"


[tool.setuptools]

# Project packages & sources

packages = {find = {where = ["src"], namespaces = true}}
